export interface PrebuiltList {
  value: string
  name: string
  items: string[]
}

export const PREBUILT_LISTS: PrebuiltList[] = [
  {
    value: "custom",
    name: "Custom",
    items: [],
  },
  {
    value: "block2ommsofttissue",
    name: "Block 2 OMM Soft Tissue",
    items: [
      "Suboccipital Soft Tissue Pressure and Traction (Suboccipital release)",
      "Bilateral Posterior Cervical Soft Tissue Pressure with Traction",
      "Unilateral Posterior Cervical Soft Tissue Pressure and Traction",
      "Bilateral Cervical Extensor Muscle Stretch",
      "Unilateral Cervical Extensor Muscle Stretch",
      "Cervical Traction",
      "Unilateral Thoracic and Lumbar Paraspinal Soft Tissue Pressure and Transverse Stretch",
      "Bilateral Bidirectional Paraspinal Soft Tissue Pressure and Longitudinal Stretch (Bilateral Prone Pressure/Counter Pressure)",
      "Sacral Mobilization (Sacral Rocking)",
      "Scapular Mobilization",
      "Prone Traction - Lumbosacral (Lumbosacral Traction or Lumbosacral Release)",
      "Inhibitory Pressure/Direct Inhibition (examiner will specify area)",
      "Longitudinal Arch of the Foot Stretching",
    ],
  },
  {
    value: "block2ommlymphaticsandmyofascial",
    name: "Block 2 OMM Lymphatics and Myofascial",
    items: [
      "Thoracic Inlet Release, Seated, Direct or Indirect (Steering Wheel technique)",
      "Thoracic Inlet Release, Supine, Direct or Indirect (Steering Wheel technique)",
      "Bilateral Pectoral Traction",
      "Rib Raising",
      "Anterior Cervical Arches",
      "Cervical Chain Drainage",
      "Submandibular Release",
      "Mandibular Drainage (Galbreath Technique)",
      "Auricular Drainage",
      "Alternating Nasal Pressure",
      "Trigeminal Stimulation",
      "Facial Effleurage",
      "Doming the Diaphragm",
      "Abdominal Plexus Release",
      "Mesenteric Release",
      "Colonic Stimulation",
      "Thoracic Pump",
      "Pedal Pump",
    ],
  },
  {
    value: "block2cs",
    name: "Block 2 CS",
    items: [
      "HEENT 1 - NOSE, MOUTH/PHARYNX",
      "HEENT 1 - EARS",
      "HEENT 2 - HEAD, NECK",
      "HEENT 2 - EYES",
      "CARDIOVASCULAR - CARDIOVASCULAR EXAM (PATIENT SUPINE AT 30° ANGLE)",
      "CARDIOVASCULAR - CARDIOVASCULAR EXAM (PATIENT IN SEATED POSITION)",
      "PULMONARY - PULMONARY EXAM",
    ],
  },
  {
    value: "block1ommlandmarks",
    name: "Block 1 OMM Landmarks",
    items: [
      "Inion",
      "C2 spinous process",
      "C7 spinous process",
      "Sternal angle",
      "T3 spinous process",
      "T7 spinous process",
      "Xiphoid process",
      "L4 spinous process",
      "Earlobes",
      "Mastoid processes",
      "Inferior aspect of occiput",
      "Acromion",
      "Spine of scapula",
      "Inferior angle of scapula",
      "Iliac crest",
      "Anterior superior iliac spine",
      "Posterior superior iliac spine",
      "Superior aspect of greater trochanter of femur",
      "Patella",
      "Calcaneal (Achilles) tendon",
      "Arches of the feet",
      "External auditory canal",
      "Lateral head of the humerus",
      "Lateral aspect of greater trochanter of femur",
      "Patella",
      "Lateral malleolus",
    ],
  },
  {
    value: "block1omm12step",
    name: "Block 1 OMM 12 Step",
    items: [
      "Gait analysis",
      "Static posture and palpation of paired landmarks",
      "Dynamic trunk sidebending",
      "Standing flexion test",
      "Stork test",
      "Seated flexion test",
      "Screening test of upper extremities",
      "Trunk rotation",
      "Trunk side bending",
      "Head and neck mobility",
      "Respiration of thoracic cage",
      "Lower extremity screening",
    ],
  },
  {
    value: "block1ommsofttissue",
    name: "Block 1 OMM Soft Tissue",
    items: [
      "Suboccipital Soft Tissue Pressure and Traction (Suboccipital release)",
      "Bilateral Posterior Cervical Soft Tissue Pressure with Traction",
      "Unilateral Posterior Cervical Soft Tissue Pressure and Traction",
      "Bilateral Cervical Extensor Muscle Stretch",
      "Unilateral Cervical Extensor Muscle Stretch",
      "Unilateral Transverse Stretch of Cervical Extensors",
      "Cervical Traction",
      "Unilateral Thoracic and Lumbar Paraspinal Soft Tissue Pressure and Transverse Stretch",
      "Bilateral Bidirectional Paraspinal Soft Tissue Pressure and Longitudinal Stretch (Bilateral Prone Pressure/Counter Pressure)",
      "Sacral Mobilization (Sacral Rocking)",
      "Scapular Mobilization",
      "Prone Traction - Lumbosacral (Lumbosacral Traction or Lumbosacral Release)",
      "Inhibitory Pressure/Direct Inhibition (examiner will specify area)",
      "Longitudinal Arch of the Foot Stretching",
    ],
  },
]
